#!/usr/bin/env sh
set -eu

: "${NEXT_PUBLIC_MANAGEMENT_API_URL:=/api/management}"
: "${NEXT_PUBLIC_MANAGEMENT_API_AUTH_KEY:=change-me}"
: "${NEXT_PUBLIC_CONNECTOR_NAME:=EITEL-EDC}"
: "${NEXT_PUBLIC_DSP_URL:=http://conectoruc3m:11003/api/v1/dsp/2025-1}"
: "${NEXT_PUBLIC_CONNECTOR_CATALOG_LIST:=}"
: "${NEXT_PUBLIC_DEFAULT_REMOTE_CONNECTOR:=}"
if [ -z "${NEXT_PUBLIC_CONNECTOR_DIRECTORY:-}" ]; then
  NEXT_PUBLIC_CONNECTOR_DIRECTORY='{}'
fi
: "${NEXT_PUBLIC_UI_VARIANT:=local}"
: "${NEXT_PUBLIC_ARCGIS_AUTH_ENABLED:=}"
: "${NEXT_PUBLIC_ARCGIS_PORTAL_URL:=}"
: "${NEXT_PUBLIC_ARCGIS_CLIENT_ID:=}"
: "${NEXT_PUBLIC_ARCGIS_REDIRECT_URI:=}"
: "${NEXT_PUBLIC_ARCGIS_REQUIRED_ORG_ID:=}"
: "${NEXT_PUBLIC_ARCGIS_REQUIRED_GROUP_ID:=}"

if [ -z "$NEXT_PUBLIC_ARCGIS_AUTH_ENABLED" ] && [ -n "${ARCGIS_AUTH_ENABLED:-}" ]; then
  NEXT_PUBLIC_ARCGIS_AUTH_ENABLED="$ARCGIS_AUTH_ENABLED"
fi
if [ -z "$NEXT_PUBLIC_ARCGIS_PORTAL_URL" ] && [ -n "${ARCGIS_PORTAL_URL:-}" ]; then
  NEXT_PUBLIC_ARCGIS_PORTAL_URL="$ARCGIS_PORTAL_URL"
fi
if [ -z "$NEXT_PUBLIC_ARCGIS_CLIENT_ID" ] && [ -n "${ARCGIS_CLIENT_ID:-}" ]; then
  NEXT_PUBLIC_ARCGIS_CLIENT_ID="$ARCGIS_CLIENT_ID"
fi
if [ -z "$NEXT_PUBLIC_ARCGIS_REDIRECT_URI" ] && [ -n "${ARCGIS_REDIRECT_URI:-}" ]; then
  NEXT_PUBLIC_ARCGIS_REDIRECT_URI="$ARCGIS_REDIRECT_URI"
fi
if [ -z "$NEXT_PUBLIC_ARCGIS_REQUIRED_ORG_ID" ] && [ -n "${ARCGIS_REQUIRED_ORG_ID:-}" ]; then
  NEXT_PUBLIC_ARCGIS_REQUIRED_ORG_ID="$ARCGIS_REQUIRED_ORG_ID"
fi
if [ -z "$NEXT_PUBLIC_ARCGIS_REQUIRED_GROUP_ID" ] && [ -n "${ARCGIS_REQUIRED_GROUP_ID:-}" ]; then
  NEXT_PUBLIC_ARCGIS_REQUIRED_GROUP_ID="$ARCGIS_REQUIRED_GROUP_ID"
fi

export NEXT_PUBLIC_ARCGIS_AUTH_ENABLED
export NEXT_PUBLIC_ARCGIS_PORTAL_URL
export NEXT_PUBLIC_ARCGIS_CLIENT_ID
export NEXT_PUBLIC_ARCGIS_REDIRECT_URI
export NEXT_PUBLIC_ARCGIS_REQUIRED_ORG_ID
export NEXT_PUBLIC_ARCGIS_REQUIRED_GROUP_ID

: "${NEXT_PUBLIC_STAR_MODE:=false}"
: "${NEXT_PUBLIC_STAR_COORDINATOR_NAME:=UC3M Coordinador EITEL}"
: "${NEXT_PUBLIC_STAR_COORDINATOR_URL:=}"
: "${NEXT_PUBLIC_STAR_COORDINATOR_STATUS_URL:=}"
: "${NEXT_PUBLIC_STAR_DID_METHOD:=did:key}"
: "${NEXT_PUBLIC_STAR_PARTICIPANT_DID:=}"
: "${NEXT_PUBLIC_STAR_VC_PRESENT:=false}"
: "${NEXT_PUBLIC_STAR_VC_ISSUER:=UC3M}"
: "${NEXT_PUBLIC_GAIAX_COMPLIANCE_URL:=}"

export NEXT_PUBLIC_MANAGEMENT_API_URL
export NEXT_PUBLIC_MANAGEMENT_API_AUTH_KEY
export NEXT_PUBLIC_LOCAL_ASSETS_AUTH_TOKEN
export NEXT_PUBLIC_CONNECTOR_NAME
export NEXT_PUBLIC_DSP_URL
export NEXT_PUBLIC_CONNECTOR_CATALOG_LIST
export NEXT_PUBLIC_DEFAULT_REMOTE_CONNECTOR
export NEXT_PUBLIC_CONNECTOR_DIRECTORY
export NEXT_PUBLIC_UI_VARIANT
export NEXT_PUBLIC_STAR_MODE
export NEXT_PUBLIC_STAR_COORDINATOR_NAME
export NEXT_PUBLIC_STAR_COORDINATOR_URL
export NEXT_PUBLIC_STAR_COORDINATOR_STATUS_URL
export NEXT_PUBLIC_STAR_DID_METHOD
export NEXT_PUBLIC_STAR_PARTICIPANT_DID
export NEXT_PUBLIC_STAR_VC_PRESENT
export NEXT_PUBLIC_STAR_VC_ISSUER
export NEXT_PUBLIC_GAIAX_COMPLIANCE_URL

envsubst '${NEXT_PUBLIC_MANAGEMENT_API_URL} ${NEXT_PUBLIC_MANAGEMENT_API_AUTH_KEY} ${NEXT_PUBLIC_CONNECTOR_NAME} ${NEXT_PUBLIC_DSP_URL} ${NEXT_PUBLIC_CONNECTOR_CATALOG_LIST} ${NEXT_PUBLIC_DEFAULT_REMOTE_CONNECTOR} ${NEXT_PUBLIC_CONNECTOR_DIRECTORY} ${NEXT_PUBLIC_UI_VARIANT} ${NEXT_PUBLIC_STAR_MODE} ${NEXT_PUBLIC_STAR_COORDINATOR_NAME} ${NEXT_PUBLIC_STAR_COORDINATOR_URL} ${NEXT_PUBLIC_STAR_COORDINATOR_STATUS_URL} ${NEXT_PUBLIC_STAR_DID_METHOD} ${NEXT_PUBLIC_STAR_PARTICIPANT_DID} ${NEXT_PUBLIC_STAR_VC_PRESENT} ${NEXT_PUBLIC_STAR_VC_ISSUER} ${NEXT_PUBLIC_LOCAL_ASSETS_AUTH_TOKEN} ${NEXT_PUBLIC_ARCGIS_AUTH_ENABLED} ${NEXT_PUBLIC_ARCGIS_PORTAL_URL} ${NEXT_PUBLIC_ARCGIS_CLIENT_ID} ${NEXT_PUBLIC_ARCGIS_REDIRECT_URI} ${NEXT_PUBLIC_ARCGIS_REQUIRED_ORG_ID} ${NEXT_PUBLIC_ARCGIS_REQUIRED_GROUP_ID} ${NEXT_PUBLIC_GAIAX_COMPLIANCE_URL}' \
  < /usr/share/nginx/html/config.template.js \
  > /usr/share/nginx/html/config.js
